- name: Install package dependencies
  win_chocolatey:
    name:
      - chocolatey-core.extension
      - chocolatey-windowsupdate.extension
    state: present

- name: Install Azure Cli
  win_chocolatey:
    name: azure-cli

- name: Azure login
  win_shell: az login --service-principal --username {{ az_client_id }} --password {{ az_secret }} --tenant {{ az_tenant_id }}

- name: Downloading binary files
  block:
  - name: Locating binary distrib files
    win_find: 
      paths: m:\code\chromium_git\chromium\src\cef\binary_distrib
      recurse: no 
      patterns: "*.zip"
    register: binary_distrib_files

  - ansible.builtin.debug: 
      msg: 'filename: {{ item.filename }} -- path: {{ item.path }}'
    with_items: "{{ binary_distrib_files.files }}"

  - name: Uploading binary distrib files
    win_shell: az storage blob upload --file {{ item.path }} --container-name fl-cs-web01 --name vs{{ vs_version }}/{{ item.filename }} --account-name sacsweb01
    with_items: "{{ binary_distrib_files.files }}"
