# Restart VM with setup configuration
- hosts: localhost
  connection: local
  tasks:
  - include_vars: azure_vars.yaml
  - name: "Check required variables"
    fail: msg="Variable '{{ item }}' is not defined"
    when: item not in vars
    with_items: "{{azure_required_vars}}"
  - name: Stop VM
    import_tasks: helpers/vm_stop.yaml
